export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
//FOR THE NAVBAR SEARCH
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
//FOR THE CART-MIGHT NEED ADJUSTMENTS
export const LOAD_CART = 'LOAD_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
//FOR ANY TYPES OF ALERTS NEEDED,
//JUST PASS MESSAGE/ERROR MESSAGE THROUGH THE IT/PAYLOAD
export const SET_ALERT = 'CLEAR_FILTER';
export const CLEAR_ALERT = 'CLEAR_ALERT';
